//! Pre-generated protobuf/gRPC code for Pulumi language host.
//!
//! This crate contains generated code from Pulumi's proto definitions.
//! The code was generated by tonic-build/prost and is included directly
//! rather than being regenerated at build time.

#[allow(clippy::all, rustdoc::all)]
pub mod pulumirpc {
    include!("generated/pulumirpc.rs");

    pub mod codegen {
        include!("generated/pulumirpc.codegen.rs");
    }
}

#[allow(clippy::all, rustdoc::all)]
pub mod codegen {
    include!("generated/codegen.rs");
}
