from typing import Any, Optional

def parse_template(source: str) -> dict[str, Any]: ...
def load_project(dir: str) -> dict[str, Any]: ...
def discover_project_files(dir: str) -> dict[str, Any]: ...
def has_jinja_blocks(source: str) -> bool: ...
def strip_jinja_blocks(source: str) -> str: ...
def validate_jinja(source: str, filename: str) -> None: ...
def preprocess_jinja(source: str, filename: str, context: dict[str, Any]) -> str: ...
def evaluate_builtin(name: str, args: Any) -> Any: ...
def create_execution_plan(project_dir: str, jinja_context: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...
